version: "3"

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    environment:
      DEBUG: 1
    command:
      gunicorn {{ cookiecutter.project_slug }}.wsgi --reload
  db:
    image: "postgres:16-alpine"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB={{ cookiecutter.project_slug }}
    ports:
      - "5434:5432"

volumes:
  postgresql_data:
